pub mod chooser;
pub mod docker_help;
pub mod editor;
pub mod markdown;
pub mod notes;
pub mod registry;
pub mod terminal;
pub mod terminal_registry;
pub mod text_sync;

pub type PanelInputCallback = std::rc::Rc<dyn Fn(&[u8])>;
pub type PanelTitleCallback = std::rc::Rc<dyn Fn(&str)>;

pub use terminal_registry::TerminalRef;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SshConnectionState {
    Disconnected,
    Connecting,
    Connected,
}

pub type PanelSshStateCallback = std::rc::Rc<dyn Fn(SshConnectionState)>;

/// Invoked with `true` when the panel reports a foreground command is running
/// and `false` when the shell returns to the prompt.
pub type PanelStatusCallback = std::rc::Rc<dyn Fn(bool)>;
/// Invoked when terminal-visible output changes. Consumers should use this as
/// an invalidation signal and request only the bounded text they need.
pub type PanelOutputCallback = std::rc::Rc<dyn Fn()>;
/// Invoked with a `file://host/path` URI when the shell changes directory
/// (OSC 7). Empty string signals reset. Used to drive the footer bar.
pub type PanelCwdCallback = std::rc::Rc<dyn Fn(&str)>;

/// Trait implemented by all panel backends.
/// Each panel type creates a GTK widget and handles its lifecycle.
/// This is the contract that plugins must implement.
pub trait PanelBackend: std::fmt::Debug {
    /// Panel type identifier (e.g., "terminal", "markdown", "chooser").
    fn panel_type(&self) -> &str;

    /// The GTK widget for this panel.
    fn widget(&self) -> &gtk4::Widget;

    /// Called when the panel receives focus.
    fn on_focus(&self);

    /// Called when the panel loses focus.
    fn on_blur(&self) {}

    /// Clean up resources before this backend is replaced or removed.
    /// Called before the backend's widget is removed from the container.
    /// Terminal implementations use this to terminate child processes.
    fn shutdown(&self) {}

    /// Write input to the panel (for terminal-like panels).
    fn write_input(&self, _data: &[u8]) -> bool {
        false
    }

    /// Observe local user input generated by this panel.
    fn set_input_callback(&self, _callback: Option<PanelInputCallback>) {}

    /// Observe OSC-driven title changes emitted by the app running inside this
    /// panel (terminal OSC 0/2). Empty string signals title reset/clear.
    fn set_title_callback(&self, _callback: Option<PanelTitleCallback>) {}

    /// Observe foreground-command state transitions derived from OSC 133
    /// shell integration: `true` = command running, `false` = shell prompt.
    /// Non-terminal panels leave this as no-op.
    fn set_status_callback(&self, _callback: Option<PanelStatusCallback>) {}

    /// Observe terminal output invalidations without streaming output text.
    fn set_output_callback(&self, _callback: Option<PanelOutputCallback>) {}

    /// Observe OSC 7 current-directory-URI updates so the host can render
    /// `user@host:path` in the panel footer. Empty string = footer hidden.
    fn set_cwd_callback(&self, _callback: Option<PanelCwdCallback>) {}

    /// Get current text content for recording/alert scanning.
    fn get_text_content(&self) -> Option<String> {
        None
    }

    /// Replace the complete editable text while preserving the backend's
    /// normal dirty tracking and undo integration.
    fn replace_text_content(&self, _text: &str) -> bool {
        false
    }

    /// Whether this panel supports text input.
    fn accepts_input(&self) -> bool {
        false
    }

    /// Whether this panel type opts into the sync-input feature. Returning
    /// `false` (default) hides the per-panel sync toggle in the title bar
    /// and keeps the panel out of any synced group. Backends that mirror
    /// keystrokes between panels (terminals, code editor, markdown editor)
    /// override this to return `true`.
    fn supports_sync(&self) -> bool {
        false
    }

    /// SSH connection label if this panel is remote (e.g. "user@host").
    /// Returns None for local panels.
    fn ssh_label(&self) -> Option<String> {
        None
    }

    /// Runtime SSH connection state for panels that have a saved SSH target.
    /// `None` means no SSH control should be shown.
    fn ssh_is_connected(&self) -> Option<bool> {
        None
    }

    fn ssh_connection_state(&self) -> Option<SshConnectionState> {
        self.ssh_is_connected().map(|connected| {
            if connected {
                SshConnectionState::Connected
            } else {
                SshConnectionState::Disconnected
            }
        })
    }

    /// Ask the backend to connect to its saved SSH target.
    fn ssh_connect(&self) -> bool {
        false
    }

    /// Ask the backend to disconnect from its active SSH target.
    fn ssh_disconnect(&self) -> bool {
        false
    }

    fn set_ssh_state_callback(&self, _callback: Option<PanelSshStateCallback>) {}

    /// Stable per-panel UUID. Returned by panels that participate in
    /// per-panel persistence (terminal command history, …). Default
    /// `None`: panels without persistence.
    fn panel_uuid(&self) -> Option<uuid::Uuid> {
        None
    }

    /// Optional footer text shown at the bottom of the panel frame (e.g. file
    /// path for document panels, cwd for terminals). Returns `None` to keep
    /// the footer hidden. Called once from `PanelHost::set_backend`; panels
    /// that need live updates (like VTE with OSC 7) should still drive the
    /// footer via `host.set_footer()` from their own signal handlers.
    fn footer_text(&self) -> Option<String> {
        None
    }

    /// If `Some(prompt)`, the panel is asking the caller to show a
    /// confirmation dialog with this text before the panel is closed
    /// permanently. Returning `None` (default) means "close immediately".
    ///
    /// Only consulted on permanent close (user action like Ctrl+W), not on
    /// backend swaps triggered by app shutdown.
    fn close_confirmation(&self) -> Option<String> {
        None
    }

    /// Called exactly once, AFTER `shutdown()`, when the panel is being
    /// removed permanently (not on a backend swap). Backends use this to
    /// delete any persisted state tied to this panel instance.
    fn on_permanent_close(&self) {}
}
