pub mod chooser;
pub mod editor;
pub mod markdown;
pub mod registry;
pub mod terminal;

pub type PanelInputCallback = std::rc::Rc<dyn Fn(&[u8])>;

/// Trait implemented by all panel backends.
/// Each panel type creates a GTK widget and handles its lifecycle.
/// This is the contract that plugins must implement.
pub trait PanelBackend: std::fmt::Debug {
    /// Panel type identifier (e.g., "terminal", "markdown", "chooser").
    fn panel_type(&self) -> &str;

    /// The GTK widget for this panel.
    fn widget(&self) -> &gtk4::Widget;

    /// Called when the panel receives focus.
    fn on_focus(&self);

    /// Called when the panel loses focus.
    fn on_blur(&self) {}

    /// Write input to the panel (for terminal-like panels).
    fn write_input(&self, _data: &[u8]) -> bool {
        false
    }

    /// Observe local user input generated by this panel.
    fn set_input_callback(&self, _callback: Option<PanelInputCallback>) {}

    /// Get current text content for recording/alert scanning.
    fn get_text_content(&self) -> Option<String> {
        None
    }

    /// Whether this panel supports text input.
    fn accepts_input(&self) -> bool {
        false
    }

    /// SSH connection label if this panel is remote (e.g. "user@host").
    /// Returns None for local panels.
    fn ssh_label(&self) -> Option<String> {
        None
    }

    /// Optional footer text shown at the bottom of the panel frame (e.g. file
    /// path for document panels, cwd for terminals). Returns `None` to keep
    /// the footer hidden. Called once from `PanelHost::set_backend`; panels
    /// that need live updates (like VTE with OSC 7) should still drive the
    /// footer via `host.set_footer()` from their own signal handlers.
    fn footer_text(&self) -> Option<String> {
        None
    }
}
